from typing import Union, TypeAlias

from lagrange.client.events.service import (
    ClientOnline,
    ClientOffline,
    ServerKick,
)
from lagrange.client.events.group import (
    GroupMessage,
    GroupRecall,
    # GroupNudge,
    # GroupSign,
    # GroupMuteMember,
    # GroupMemberJoinRequest,
    # GroupMemberJoined,
    # GroupMemberQuit,
    # GroupMemberGotSpecialTitle,
    # GroupNameChanged,
    # GroupReaction,
    # GroupAlbumUpdate,
    # GroupInvite,
    # GroupMemberJoinedByInvite,
)
from lagrange.client.events.friend import (
    FriendMessage,
    # FriendNudge,
)
from lagrange.client.message.elems import (
    Text,
    Quote,
    Json,
    # Service,
    AtAll,
    At,
    Image,
    Video,
    Audio,
    Raw,
    Emoji,
    # Reaction,
    Poke,
    MarketFace,
    # File,
)

AVAILABLE_EVENTS = (
    ClientOnline,
    ClientOffline,
    ServerKick,
    GroupMessage,
    GroupRecall,
    # GroupNudge,
    # GroupSign,
    # GroupMuteMember,
    # GroupMemberJoinRequest,
    # GroupMemberJoined,
    # GroupMemberQuit,
    # GroupMemberGotSpecialTitle,
    # GroupNameChanged,
    # GroupReaction,
    # GroupAlbumUpdate,
    # GroupInvite,
    # GroupMemberJoinedByInvite,
    FriendMessage,
    # FriendNudge,
)
Event: TypeAlias = Union[
    ClientOnline,
    ClientOffline,
    ServerKick,
    GroupMessage,
    GroupRecall,
    # GroupNudge,
    # GroupSign,
    # GroupMuteMember,
    # GroupMemberJoinRequest,
    # GroupMemberJoined,
    # GroupMemberQuit,
    # GroupMemberGotSpecialTitle,
    # GroupNameChanged,
    # GroupReaction,
    # GroupAlbumUpdate,
    # GroupInvite,
    # GroupMemberJoinedByInvite,
    FriendMessage,
    # FriendNudge,
]

AVAILABLE_MSG_ELEMENTS = (
    Text,
    Quote,
    Json,
    # Service,
    AtAll,
    At,
    Image,
    Video,
    Audio,
    Raw,
    Emoji,
    # Reaction,
    Poke,
    MarketFace,
    # File,
)
Element: TypeAlias = Union[
    Text,
    Quote,
    Json,
    # Service,
    AtAll,
    At,
    Image,
    Video,
    Audio,
    Raw,
    Emoji,
    # Reaction,
    Poke,
    MarketFace,
    # File,
]
